# Generated by Django 5.2.15 on 2026-06-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='action_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='key_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
