# Generated by Django 5.2.15 on 2026-07-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
    ]
