import {
    Document,
    Page,
    Text,
    View,
} from "@react-pdf/renderer";

import styles from "./pdfStyles";

function ReportDocument({

    filename,

    summary,

    keyPoints = [],

    actionItems = [],

}) {

    return (

        <Document>

            <Page
                size="A4"
                style={styles.page}
            >

                {/* Header */}

                <View style={styles.header}>

                    <Text style={styles.title}>

                        NightBat AI

                    </Text>

                    <Text style={styles.subtitle}>

                        Professional Document Analysis Report

                    </Text>

                </View>

                {/* Document Info */}

                <View style={styles.infoCard}>

                    <Text style={styles.infoTitle}>

                        Document

                    </Text>

                    <Text>

                        {filename}

                    </Text>

                    <Text
                        style={{
                            marginTop: 10,
                            color: "#06B6D4",
                            fontWeight: "bold",
                        }}
                    >

                        Generated

                    </Text>

                    <Text>

                        {new Date().toLocaleString()}

                    </Text>

                </View>

                {/* Summary */}

                <View style={styles.section}>

                    <Text style={styles.sectionTitle}>

                        Summary

                    </Text>

                    <Text style={styles.body}>

                        {summary || "No summary available."}

                    </Text>

                </View>

                {/* Key Points */}

                <View style={styles.section}>

                    <Text style={styles.sectionTitle}>

                        Key Points

                    </Text>

                    {

                        keyPoints.length === 0

                            ? (

                                <Text style={styles.body}>

                                    No key points available.

                                </Text>

                            )

                            : (

                                keyPoints.map((point, index) => (

                                    <Text
                                        key={index}
                                        style={styles.bullet}
                                    >

                                        • {point}

                                    </Text>

                                ))

                            )

                    }

                </View>

                {/* Action Items */}

                <View style={styles.section}>

                    <Text style={styles.sectionTitle}>

                        Action Items

                    </Text>

                    {

                        actionItems.length === 0

                            ? (

                                <Text style={styles.body}>

                                    No action items available.

                                </Text>

                            )

                            : (

                                actionItems.map((item, index) => (

                                    <Text
                                        key={index}
                                        style={styles.bullet}
                                    >

                                        ✓ {item}

                                    </Text>

                                ))

                            )

                    }

                </View>

                {/* Footer */}

                <View
                    fixed
                    style={styles.footer}
                >

                    <Text>

                        Generated by NightBat AI

                    </Text>

                    <Text
                        render={({ pageNumber, totalPages }) =>
                            `Page ${pageNumber} of ${totalPages}`
                        }
                    />

                </View>

            </Page>

        </Document>

    );

}

export default ReportDocument;